name: Test ROS 2 CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test the ROS 2 CI
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Test the ROS 2 CI
        uses: ./