name: Workflows Test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  workflows-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rosdistro : [foxy,galactic]
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Testing the default configuration
        uses: ./
      - name: Testing with different distribution
        uses: ./
        with:
          ros2-distro: ${{ matrix.rosdistro }}
