name: Workflows Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  workflows-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Testing the default configuration
        uses: ./
      - name: Testing with different distribution
        uses: ./
        with:
          ros2-distro: rolling
      - name: Testing with commands
        uses: ./
        with:
          pre-install: FOO=fofofo
          post-install: test "${FOO}" = 'fofofo'
          pre-build: apt-get update && apt-get install -y neofetch && neofetch
          post-build: cat ./LICENSE && cat ./README.md
          pre-test: GOO=gogogo
          post-test: test "${FOO}${GOO}" = 'fofofogogogo'
      - name: Testing with APT and pip install
        uses: ./
        with:
          apt-packages: neofetch libopencv-dev
          pip-packages: numpy matplotlib
          post-install: neofetch && opencv_version && python3 -c 'import numpy; import matplotlib'
      - name: Testing with including external project
        uses: ./
        with:
          ros2-distro: foxy
          apt-packages: git ros-foxy-example-interfaces
          pre-build: git clone -b foxy https://github.com/ros2/examples /ws/examples
